# Generated by Django 3.1.3 on 2021-02-05 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BITCOIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='日付')),
                ('high', models.FloatField(null=True, verbose_name='高値')),
                ('low', models.FloatField(null=True, verbose_name='安値')),
                ('open', models.FloatField(null=True, verbose_name='始値')),
                ('close', models.FloatField(null=True, verbose_name='終値')),
                ('volume', models.FloatField(null=True, verbose_name='出来高')),
            ],
        ),
        migrations.CreateModel(
            name='NIKKEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='日付')),
                ('high', models.FloatField(null=True, verbose_name='高値')),
                ('low', models.FloatField(null=True, verbose_name='安値')),
                ('open', models.FloatField(null=True, verbose_name='始値')),
                ('close', models.FloatField(null=True, verbose_name='終値')),
                ('volume', models.FloatField(null=True, verbose_name='出来高')),
            ],
        ),
        migrations.CreateModel(
            name='SP500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='日付')),
                ('high', models.FloatField(null=True, verbose_name='高値')),
                ('low', models.FloatField(null=True, verbose_name='安値')),
                ('open', models.FloatField(null=True, verbose_name='始値')),
                ('close', models.FloatField(null=True, verbose_name='終値')),
                ('volume', models.FloatField(null=True, verbose_name='出来高')),
            ],
        ),
        migrations.CreateModel(
            name='USDJPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='日付')),
                ('high', models.FloatField(null=True, verbose_name='高値')),
                ('low', models.FloatField(null=True, verbose_name='安値')),
                ('open', models.FloatField(null=True, verbose_name='始値')),
                ('close', models.FloatField(null=True, verbose_name='終値')),
                ('volume', models.FloatField(null=True, verbose_name='出来高')),
            ],
        ),
    ]
