# Generated by Django 3.1.3 on 2021-02-08 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMMON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='日付')),
                ('nikkei', models.FloatField(null=True, verbose_name='日経225')),
                ('sp500', models.FloatField(null=True, verbose_name='S&P500')),
                ('usdjpy', models.FloatField(null=True, verbose_name='USD/JPY')),
                ('bitcoin', models.FloatField(null=True, verbose_name='BITCOIN')),
            ],
        ),
    ]
